project_id  = "probable-scout-446005-v7"
region      = "us-central1"
zone        = "us-central1-a"
service_account_email = "terraform@probable-scout-446005-v7.iam.gserviceaccount.com"
db_username  = "puppeteer"
db_password  = "s8ear72IWC4QHiZH"
db_name      = "analytics_puppeteer"